<?php
	if (!defined("CROSSBROWDY_WEB") || CROSSBROWDY_WEB !== "YES") { exit(); }

	define("DOWNLOAD_FOLDER", "download/");
	define("DOWNLOAD_FOLDER_REAL", "files/");

	define("EXAMPLES_FILENAME_BASE", "CrossBrowdy_examples");
	define("EXAMPLES_FILENAME_PATH_ZIP", DOWNLOAD_FOLDER . EXAMPLES_FILENAME_BASE . ".zip");
	define("EXAMPLES_FILENAME_PATH_ZIP_REAL", DOWNLOAD_FOLDER_REAL . EXAMPLES_FILENAME_BASE . ".zip");
	
	define("CB_VERSION_CURRENT", "0.99.96.35");
	define("CB_FILENAME_BASE", "CrossBrowdy_{VERSION}");
	define("CB_FILENAME_PATH_ZIP", DOWNLOAD_FOLDER . CB_FILENAME_BASE . ".zip");
	define("CB_FILENAME_PATH_ZIP_DIST", DOWNLOAD_FOLDER . CB_FILENAME_BASE . ".dist.zip");
	define("CB_FILENAME_PATH_ZIP_REAL", DOWNLOAD_FOLDER_REAL . CB_FILENAME_BASE . ".zip");
	define("CB_FILENAME_PATH_ZIP_REAL_DIST", DOWNLOAD_FOLDER_REAL . CB_FILENAME_BASE . ".dist.zip");
	
	define("CB_FILENAME_BASE_LATEST", str_replace("{VERSION}", CB_VERSION_CURRENT, CB_FILENAME_BASE));
	define("CB_FILENAME_PATH_ZIP_LATEST", str_replace("{VERSION}", CB_VERSION_CURRENT, CB_FILENAME_PATH_ZIP));
	define("CB_FILENAME_PATH_ZIP_LATEST_DIST", str_replace("{VERSION}", CB_VERSION_CURRENT, CB_FILENAME_PATH_ZIP_DIST));
	define("CB_FILENAME_PATH_ZIP_REAL_LATEST", str_replace("{VERSION}", CB_VERSION_CURRENT, CB_FILENAME_PATH_ZIP_REAL));
	define("CB_FILENAME_PATH_ZIP_REAL_LATEST_DIST", str_replace("{VERSION}", CB_VERSION_CURRENT, CB_FILENAME_PATH_ZIP_REAL_DIST));
